[package]
name = "rust_cpu_emulator"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
regex = "1.10.4"
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }